--Localization.deDE.lua
--Localization by X

if GetLocale() == "deDE" then

 RareAnnouncerLocalization = {
	["71864"] = "Spelurk",
	["71919"] = "Zhu-Gon der Saure",
	["72045"] = "Chelon",
	["72048"] = "Klapperknochen",
	["72049"] = "Kranichknirscher",
	["72193"] = "Karkanos",
	["72245"] = "Zesqua",
	["72769"] = "Jadefeuergeist",
	["72775"] = "Bufo",
	["72808"] = "Tsavo'ka <Geist in der Dunkelheit>",
	["72909"] = "Gu'chi der Schwarmbringer",
	["72970"] = "Golganarr",
	["73157"] = "Steinmoos",
	["73158"] = "Smaragdkranich",
	["73160"] = "Eisenfellstahlhorn",
	["73161"] = "Großschildkröte Zornpanzer",
	["73163"] = "Kaiserpython",
	["73166"] = "Monströse Dornzange",
	["73167"] = "Huolon",
	["73169"] = "Jakur von Ordos",
	["73170"] = "Behüter Osu",
	["73171"] = "Champion der Schwarzen Flamme",
	["73172"] = "Funkenlord Gairan",
	["73173"] = "Urdur der Kauterisierer",
	["73174"] = "Archiereus der Flamme",
	["73175"] = "Glutfall",
	["73277"] = "Blattheiler",
	["73279"] = "Tiefenschlund",
	["73281"] = "Schreckensschiff Vazuvius",
	["73282"] = "Garnia",
	["73704"] = "Stinkezopf",
	ago = "vorher.",
	Alive = "Lebendig",
	announce = "Melden, wenn Sie einen seltenen Gegner ins Ziel nehmen oder wenn ein seltener Gegner stirbt.",
	Coordinates = "Koordinaten:",
	Dead = "Tot",
	["has died"] = " wurde getötet.",
	hidetracking = "Verfolgungsfenster im Kampf ausblenden.",
	Killed = "Getötet",
	["last killed"] = "wurde zuletzt getötet",
	optionsConfig = "Konfiguration",
	optionsTracking = "Zielverfolgung",
	recentkill = "wurde vor weniger als einer Minute zuletzt getötet.",
	respond = "Auf Anfragen antworten. ",
	responedRT = "Auf Raretime/Raretimer Anfragen antworten.",
	setTomTom = "TomTom Wegpunkt setzen, wenn ein seltener Gegner erfasst wird, den Sie nicht anvisieren",
	trackNotice = "|c0000FDEENote: Die folgende Liste wird nur verwendet, wenn die Option 'Auswahl' aktiv ist",
	trackSelectAll = "Alle auswählen",
	trackSelectNone = "Nichts auswählen",
	trackTypeAll = "Alle",
	trackTypeAllTooltip = "Alle bekannten Gegner anzeigen",
	trackTypeHead = "Art der Zielverfolgung",
	trackTypeNext = "Nächster erscheinender Gegner",
	trackTypeNextTooltip = "Nur Gegner anzeigen, die aufgrund des Timers wieder erscheinen können",
	trackTypeSelected = "Auswahl",
	trackTypeSelectedTooltip = "Nur ausgewählte Gegner anzeigen",
}

end
