if GetLocale() == "itIT" then
 RareAnnouncerLocalization = {
	["71864"] = "Spelurk", -- Requires localization
	["71919"] = "Zhu-Gon the Sour", -- Requires localization
	["72045"] = "Chelon", -- Requires localization
	["72048"] = "Rattleskew", -- Requires localization
	["72049"] = "Cranegnasher", -- Requires localization
	["72193"] = "Karkanos", -- Requires localization
	["72245"] = "Zesqua", -- Requires localization
	["72769"] = "Spirit of Jadefire", -- Requires localization
	["72775"] = "Bufo", -- Requires localization
	["72808"] = "Tsavo'ka <Ghost in the Darkness>", -- Requires localization
	["72909"] = "Gu'chi the Swarmbringer", -- Requires localization
	["72970"] = "Golganarr", -- Requires localization
	["73157"] = "Rock Moss", -- Requires localization
	["73158"] = "Emerald Gander", -- Requires localization
	["73160"] = "Ironfur Steelhorn", -- Requires localization
	["73161"] = "Great Turtle Furyshell", -- Requires localization
	["73163"] = "Imperial Python", -- Requires localization
	["73166"] = "Monsterous Spineclaw", -- Requires localization
	["73167"] = "Huolon", -- Requires localization
	["73169"] = "Jakur of Ordon", -- Requires localization
	["73170"] = "Watcher Osu", -- Requires localization
	["73171"] = "Champion of the Blackflame", -- Requires localization
	["73172"] = "Flintlord Gairan", -- Requires localization
	["73173"] = "Urdur the Cauterizer", -- Requires localization
	["73174"] = "Archiereus of Flame", -- Requires localization
	["73175"] = "Cinderfall", -- Requires localization
	["73277"] = "Leafmender", -- Requires localization
	["73279"] = "Evermaw", -- Requires localization
	["73281"] = "Dread Ship Vazuvius", -- Requires localization
	["73282"] = "Garnia", -- Requires localization
	["73704"] = "Stinkbraid", -- Requires localization
	ago = "ago.", -- Requires localization
	Alive = "Alive", -- Requires localization
	announce = "Announce when you target a rare or when a rare dies.", -- Requires localization
	Coordinates = "Coordinates:", -- Requires localization
	Dead = "Dead", -- Requires localization
	["has died"] = "has died.", -- Requires localization
	hidetracking = "Hide tracking window while in combat.", -- Requires localization
	Killed = "Killed", -- Requires localization
	["last killed"] = "was last killed", -- Requires localization
	optionsConfig = "Config", -- Requires localization
	optionsTracking = "Tracking", -- Requires localization
	recentkill = "was last killed less than a minute ago.", -- Requires localization
	respond = "Respond to requests.", -- Requires localization
	responedRT = "Respond to raretime / raretimer requests.", -- Requires localization
	setTomTom = "Set TomTom waypoint when a rare is found that you are not targetting.", -- Requires localization
	trackNotice = "|c0000FDEENote: The below selection is only adhered to when 'Selected' is chosen above", -- Requires localization
	trackSelectAll = "Select All", -- Requires localization
	trackSelectNone = "Select None", -- Requires localization
	trackTypeAll = "All", -- Requires localization
	trackTypeAllTooltip = "Show all known rares", -- Requires localization
	trackTypeHead = "Tracking Type", -- Requires localization
	trackTypeNext = "Next to spawn", -- Requires localization
	trackTypeNextTooltip = "Only show rares ready to spawn according to timer", -- Requires localization
	trackTypeSelected = "Selected", -- Requires localization
	trackTypeSelectedTooltip = "Show only selected rares", -- Requires localization
}

end
