if GetLocale() == "frFR" then
 RareAnnouncerLocalization = {
	["71864"] = "Souterrant", -- Needs review
	["71919"] = "Zhu Gon l’Amer", -- Needs review
	["72045"] = "Chelon", -- Needs review
	["72048"] = "Déglingois", -- Needs review
	["72049"] = "Croque-grue", -- Needs review
	["72193"] = "Karkanos", -- Needs review
	["72245"] = "Zesqua", -- Needs review
	["72769"] = "Esprit de Jadefeu", -- Needs review
	["72775"] = "Bufo", -- Needs review
	["72808"] = "Tsavo’ka", -- Needs review
	["72909"] = "Gu’chi l’Essaimeur", -- Needs review
	["72970"] = "Golganarr", -- Needs review
	["73157"] = "Mousse des rochers", -- Needs review
	["73158"] = "Jars émeraude", -- Needs review
	["73160"] = "Corne-d’acier ferpoil", -- Needs review
	["73161"] = "Grande tortue Écaille-de-Fureur", -- Needs review
	["73163"] = "Python impérial", -- Needs review
	["73166"] = "Pincépine monstrueux", -- Needs review
	["73167"] = "Huolon", -- Needs review
	["73169"] = "Jakur d’Ordos", -- Needs review
	["73170"] = "Guetteur Osu", -- Needs review
	["73171"] = "Champion de la flamme noire", -- Needs review
	["73172"] = "Seigneur des silex Gairan", -- Needs review
	["73173"] = "Urdur le Cautérisateur", -- Needs review
	["73174"] = "Archiprêtre de flammes", -- Needs review
	["73175"] = "Cendrechute", -- Needs review
	["73277"] = "Soigne-Feuille", -- Needs review
	["73279"] = "Gueule-Éternelle", -- Needs review
	["73281"] = "Bateau de l’effroi Vazuvius", -- Needs review
	["73282"] = "Garnia", -- Needs review
	["73704"] = "Fouettnatte", -- Needs review
	ago = ".", -- Needs review
	Alive = "En vie", -- Needs review
	announce = "Annoncer quand je cible un rare ou qu'un rare meurt.", -- Needs review
	Coordinates = "Coordonnées:", -- Needs review
	Dead = "Mort", -- Needs review
	["has died"] = "a succombé.", -- Needs review
	hidetracking = "Cacher la fenêtre de pistage en combat.", -- Needs review
	Killed = "Tué", -- Needs review
	["last killed"] = "a été tué il y a", -- Needs review
	optionsConfig = "Configuration", -- Needs review
	optionsTracking = "Pistage", -- Needs review
	recentkill = "a été tué il y a moins d'une minute.", -- Needs review
	respond = "Répondre aux requêtes.", -- Needs review
	responedRT = "Répondre aux requêtes raretime / raretimer.", -- Needs review
	setTomTom = "Configurer un trajet TomTom quand un rare que je ne cible pas est trouvé.", -- Needs review
	trackNotice = "|c0000FDEENote: La sélection ci-dessous ne s'applique que lorsque 'Sélectionné' est choisi ci-dessus", -- Needs review
	trackSelectAll = "Sélectionner tous", -- Needs review
	trackSelectNone = "Sélectionner aucun", -- Needs review
	trackTypeAll = "Tous", -- Needs review
	trackTypeAllTooltip = "Montrer tous les rares connus", -- Needs review
	trackTypeHead = "Type de pistage", -- Needs review
	trackTypeNext = "Prochain à apparaître", -- Needs review
	trackTypeNextTooltip = "Ne montrer que les rares prêts à apparaître selon le minuteur", -- Needs review
	trackTypeSelected = "Sélectionné", -- Needs review
	trackTypeSelectedTooltip = "Ne montrer que les rares sélectionnés", -- Needs review
}

end
