if GetLocale() == "zhCN" then
 RareAnnouncerLocalization = {
	["71864"] = "斯普鲁克",
	["71919"] = "泛酸的筑汞",
	["72045"] = "蛰龙",
	["72048"] = "响骨",
	["72049"] = "噬鹤者",
	["72193"] = "卡卡诺斯",
	["72245"] = "泽泉",
	["72769"] = "玉火之灵",
	["72775"] = "布佛",
	["72808"] = "查沃卡",
	["72909"] = "虫群先锋古赤",
	["72970"] = "高戈纳尔",
	["73157"] = "石苔",
	["73158"] = "翠羽公鹤",
	["73160"] = "铁鬃钢角牛",
	["73161"] = "怒壳巨龟",
	["73163"] = "帝王巨蟒",
	["73166"] = "凶暴钳爪蟹",
	["73167"] = "惑龙",
	["73169"] = "神战士迦库尔",
	["73170"] = "斥候奥苏",
	["73171"] = "黑火勇士",
	["73172"] = "燧石领主铠兰",
	["73173"] = "烙印者乌都尔",
	["73174"] = "烈焰祭司阿克鲁斯",
	["73175"] = "落烬",
	["73277"] = "剪叶者",
	["73279"] = "吞天",
	["73281"] = "幽灵船瓦祖维斯号",
	["73282"] = "加尼亚",
	["73704"] = "斯汀克布莱德",
	ago = "之前.", -- Needs review
	Alive = "存活",
	announce = "当你选中稀有或击杀稀有时通报", -- Needs review
	Coordinates = "坐标：", -- Needs review
	Dead = "死亡",
	["has died"] = "已死", -- Needs review
	hidetracking = "战斗中隐藏追踪窗口", -- Needs review
	Killed = "已击杀", -- Needs review
	["last killed"] = "最后击杀", -- Needs review
	optionsConfig = "设置", -- Needs review
	optionsTracking = "追踪", -- Needs review
	recentkill = "距最后击杀不到一分钟.", -- Needs review
	respond = "回应要求", -- Needs review
	responedRT = "回应稀有击杀记录要求", -- Needs review
	setTomTom = "当发现稀有时设置TomTom路径点到目标", -- Needs review
	trackNotice = "|c0000FDEE注意: 以下的选择只有当上面的选择为 \\\"仅选择\\\" 时生效", -- Needs review
	trackSelectAll = "选择全部", -- Needs review
	trackSelectNone = "清空选择", -- Needs review
	trackTypeAll = "所有", -- Needs review
	trackTypeAllTooltip = "显示所有已知稀有", -- Needs review
	trackTypeHead = "追踪方式", -- Needs review
	trackTypeNext = "准备重生", -- Needs review
	trackTypeNextTooltip = "只显示根据计时器判断准备重生的稀有", -- Needs review
	trackTypeSelected = "仅选择", -- Needs review
	trackTypeSelectedTooltip = "只显示选择的稀有", -- Needs review
}

end
